"""The forward and backward pass, on networks a human can check with a pencil.

Every expected value in this file was worked out by hand and written down. None
of it is generated by the code under test -- a test whose expectation comes from
the implementation only proves the implementation is consistent with itself.

Calendar reference for June 2026 (used throughout):

    Mo Tu We Th Fr Sa Su
     1  2  3  4  5  6  7
     8  9 10 11 12 13 14
    15 16 17 18 19 20 21
    22 23 24 25 26 27 28
    29 30
"""

from __future__ import annotations

from datetime import date

import pytest

from massingplan.core.constraints import ConstraintType
from massingplan.core.cpm import calculate, summarise
from massingplan.core.graph import ScheduleCycleError
from massingplan.core.issues import IssueLog
from massingplan.core.network import (
    ActivityKind,
    LagCalendar,
    Link,
    ProgressMode,
    RelationType,
    SchedulerOptions,
    Task,
)
from massingplan.core.timeaxis import WorkCalendar, WorkPattern, day_of

JUN1 = date(2026, 6, 1)  # a Monday


def d(result, aid: str) -> tuple[date, date]:  # type: ignore[no-untyped-def]
    """(start, last day worked) for an activity -- the human-readable span."""
    return day_of(result.early_start[aid]), day_of(result.early_finish[aid] - 1)


# -- the basics -----------------------------------------------------------


def test_a_single_five_day_task_runs_monday_to_friday(five_day) -> None:  # type: ignore[no-untyped-def]
    result = calculate([Task("A", "Excavate", 5, "5D")], [], {"5D": five_day}, data_date=JUN1)
    assert d(result, "A") == (date(2026, 6, 1), date(2026, 6, 5))
    assert result.total_float_days["A"] == 0
    assert result.is_critical("A")


def test_a_chain_of_three_is_the_sum_of_its_durations(five_day) -> None:  # type: ignore[no-untyped-def]
    """A(3) -> B(2) -> C(4) = 9 working days: Mon 1 Jun to Thu 11 Jun."""
    tasks = [Task("A", "", 3, "5D"), Task("B", "", 2, "5D"), Task("C", "", 4, "5D")]
    links = [Link("A", "B"), Link("B", "C")]
    result = calculate(tasks, links, {"5D": five_day}, data_date=JUN1)

    assert d(result, "A") == (date(2026, 6, 1), date(2026, 6, 3))
    assert d(result, "B") == (date(2026, 6, 4), date(2026, 6, 5))
    assert d(result, "C") == (date(2026, 6, 8), date(2026, 6, 11))  # skips the weekend
    assert result.critical_ids == ["A", "B", "C"]
    assert result.longest_path() == ["A", "B", "C"]


def test_a_parallel_branch_carries_float(five_day) -> None:  # type: ignore[no-untyped-def]
    """START -> {LONG(10), SHORT(4)} -> END. SHORT has six working days of float."""
    tasks = [
        Task("START", "", 1, "5D"),
        Task("LONG", "", 10, "5D"),
        Task("SHORT", "", 4, "5D"),
        Task("END", "", 1, "5D"),
    ]
    links = [
        Link("START", "LONG"),
        Link("START", "SHORT"),
        Link("LONG", "END"),
        Link("SHORT", "END"),
    ]
    result = calculate(tasks, links, {"5D": five_day}, data_date=JUN1)

    assert result.total_float_days["LONG"] == 0
    assert result.total_float_days["SHORT"] == 6
    assert result.free_float_days["SHORT"] == 6
    assert result.longest_path() == ["START", "LONG", "END"]
    assert result.is_critical("SHORT") is False


def test_free_float_is_smaller_than_total_float_on_a_shared_path(five_day) -> None:  # type: ignore[no-untyped-def]
    """A -> B -> END, with END also driven by a longer branch.

    A and B each have total float, but only B has free float: A's slack is
    B's to spend, not A's.
    """
    tasks = [
        Task("A", "", 2, "5D"),
        Task("B", "", 2, "5D"),
        Task("LONG", "", 10, "5D"),
        Task("END", "", 1, "5D"),
    ]
    links = [Link("A", "B"), Link("B", "END"), Link("LONG", "END")]
    result = calculate(tasks, links, {"5D": five_day}, data_date=JUN1)

    assert result.total_float_days["A"] == 6
    assert result.total_float_days["B"] == 6
    assert result.free_float_days["A"] == 0  # spending it would delay B
    assert result.free_float_days["B"] == 6


# -- the four relationship types ------------------------------------------


def test_all_four_relationship_types_by_hand(five_day) -> None:  # type: ignore[no-untyped-def]
    """P runs Mon 1 to Fri 5 June. Each successor is 2 days on the same calendar.

    FS: starts after P finishes           -> Mon 8, Tue 9
    SS: starts when P starts              -> Mon 1, Tue 2
    FF: finishes when P finishes          -> Thu 4, Fri 5
    SF: finishes when P starts            -> the finish is bounded at Mon 1, so
        the work is Thu 28 May to Fri 29 May -- but the data date floors it to
        Mon 1 June, which is the correct and more useful answer.
    """
    cals = {"5D": five_day}
    p = Task("P", "", 5, "5D")

    fs = calculate(
        [p, Task("S", "", 2, "5D")], [Link("P", "S", RelationType.FS)], cals, data_date=JUN1
    )
    assert d(fs, "S") == (date(2026, 6, 8), date(2026, 6, 9))

    ss = calculate(
        [p, Task("S", "", 2, "5D")], [Link("P", "S", RelationType.SS)], cals, data_date=JUN1
    )
    assert d(ss, "S") == (date(2026, 6, 1), date(2026, 6, 2))

    ff = calculate(
        [p, Task("S", "", 2, "5D")], [Link("P", "S", RelationType.FF)], cals, data_date=JUN1
    )
    assert d(ff, "S") == (date(2026, 6, 4), date(2026, 6, 5))

    sf = calculate(
        [p, Task("S", "", 2, "5D")], [Link("P", "S", RelationType.SF)], cals, data_date=JUN1
    )
    # Floored by the data date rather than scheduled into the past.
    assert d(sf, "S")[0] == date(2026, 6, 1)


def test_a_lag_pushes_the_successor_out(five_day) -> None:  # type: ignore[no-untyped-def]
    """A(2) finishes Tue 2 Jun. FS+3 working days -> B starts Fri 5 Jun."""
    tasks = [Task("A", "", 2, "5D"), Task("B", "", 1, "5D")]
    result = calculate(
        tasks, [Link("A", "B", RelationType.FS, 3)], {"5D": five_day}, data_date=JUN1
    )
    assert d(result, "A") == (date(2026, 6, 1), date(2026, 6, 2))
    assert d(result, "B") == (date(2026, 6, 8), date(2026, 6, 8))


def test_a_negative_lag_is_a_lead_and_pulls_the_successor_in(five_day) -> None:  # type: ignore[no-untyped-def]
    """A(5) finishes Fri 5 Jun; FS-2 lets B start two working days earlier, Thu 4."""
    tasks = [Task("A", "", 5, "5D"), Task("B", "", 3, "5D")]
    result = calculate(
        tasks, [Link("A", "B", RelationType.FS, -2)], {"5D": five_day}, data_date=JUN1
    )
    assert d(result, "B")[0] == date(2026, 6, 4)


# -- multi-calendar --------------------------------------------------------


def test_two_calendars_produce_different_finishes_from_the_same_duration(five_day, six_day) -> None:  # type: ignore[no-untyped-def]
    """Ten days of work: Mon-Fri finishes Fri 12 June; Mon-Sat finishes Thu 11 June."""
    tasks = [Task("WEEK5", "", 10, "5D"), Task("WEEK6", "", 10, "6D")]
    result = calculate(tasks, [], {"5D": five_day, "6D": six_day}, data_date=JUN1)
    assert d(result, "WEEK5") == (date(2026, 6, 1), date(2026, 6, 12))
    assert d(result, "WEEK6") == (date(2026, 6, 1), date(2026, 6, 11))


def test_a_holiday_on_one_calendar_moves_one_branch_and_not_the_other() -> None:
    """The failure working-day offsets hide: two branches, one shutdown, one answer."""
    plain = WorkCalendar("P", "Mon-Fri", WorkPattern(frozenset({0, 1, 2, 3, 4})))
    holiday = WorkCalendar(
        "H",
        "Mon-Fri with 8 June off",
        WorkPattern(frozenset({0, 1, 2, 3, 4}), frozenset({date(2026, 6, 8)})),
    )
    tasks = [Task("CLEAR", "", 8, "P"), Task("SHUT", "", 8, "H")]
    result = calculate(tasks, [], {"P": plain, "H": holiday}, data_date=JUN1)
    assert d(result, "CLEAR") == (date(2026, 6, 1), date(2026, 6, 10))
    assert d(result, "SHUT") == (date(2026, 6, 1), date(2026, 6, 11))


def test_the_lag_calendar_choice_changes_the_answer(five_day, six_day) -> None:  # type: ignore[no-untyped-def]
    """A five-day FS lag from a Mon-Fri predecessor into a Mon-Sat successor.

    P (Mon-Fri) finishes at the end of Fri 5 June. Five working days of lag then
    elapse, and where they land depends on whose week is counted:

    * **Predecessor's calendar** (Mon-Fri): Mon 8, Tue 9, Wed 10, Thu 11, Fri 12.
      The lag ends at the close of Fri 12, so S can start **Sat 13 June** -- a
      Saturday, which is a working day on its own Mon-Sat calendar.
    * **Successor's calendar** (Mon-Sat): Sat 6, Mon 8, Tue 9, Wed 10, Thu 11.
      The lag ends at the close of Thu 11, so S starts **Fri 12 June**.

    One day is enough to miss a milestone, and neither answer looks wrong. That
    is why the choice is explicit and recorded on the result rather than assumed.
    """
    tasks = [Task("P", "", 5, "5D"), Task("S", "", 1, "6D")]
    links = [Link("P", "S", RelationType.FS, 5)]
    cals = {"5D": five_day, "6D": six_day}

    on_pred = calculate(
        tasks,
        links,
        cals,
        data_date=JUN1,
        options=SchedulerOptions(lag_calendar=LagCalendar.PREDECESSOR),
    )
    on_succ = calculate(
        tasks,
        links,
        cals,
        data_date=JUN1,
        options=SchedulerOptions(lag_calendar=LagCalendar.SUCCESSOR),
    )
    assert d(on_pred, "S")[0] == date(2026, 6, 13)
    assert d(on_succ, "S")[0] == date(2026, 6, 12)
    assert on_pred.options.lag_calendar is LagCalendar.PREDECESSOR


def test_a_twenty_four_hour_lag_counts_elapsed_days(five_day) -> None:  # type: ignore[no-untyped-def]
    """A concrete cure is a fact about chemistry, not about the working week."""
    tasks = [Task("POUR", "", 1, "5D"), Task("STRIP", "", 1, "5D")]
    links = [Link("POUR", "STRIP", RelationType.FS, 3)]
    result = calculate(
        tasks,
        links,
        {"5D": five_day},
        data_date=JUN1,
        options=SchedulerOptions(lag_calendar=LagCalendar.TWENTY_FOUR_HOUR),
    )
    # Pour Mon 1; boundary Tue 2; +3 elapsed days = Fri 5.
    assert d(result, "STRIP")[0] == date(2026, 6, 5)


# -- milestones ------------------------------------------------------------


def test_a_milestone_is_an_instant_not_a_day(five_day) -> None:  # type: ignore[no-untyped-def]
    tasks = [
        Task("WORK", "", 5, "5D"),
        Task("DONE", "Substantial completion", 0, "5D", kind=ActivityKind.FINISH_MILESTONE),
    ]
    result = calculate(tasks, [Link("WORK", "DONE")], {"5D": five_day}, data_date=JUN1)
    assert result.early_start["DONE"] == result.early_finish["DONE"]
    # The work finishes Friday; the milestone marks that boundary.
    assert day_of(result.early_start["DONE"]) == date(2026, 6, 8)


def test_a_milestone_with_a_duration_is_rejected_at_construction() -> None:
    with pytest.raises(ValueError, match="a milestone is an instant"):
        Task("M", "", 3, kind=ActivityKind.START_MILESTONE)


# -- constraints -----------------------------------------------------------


def test_start_no_earlier_than_delays_the_start(five_day) -> None:  # type: ignore[no-untyped-def]
    """Material arrives on the 10th; the work cannot begin before it."""
    tasks = [
        Task(
            "INSTALL",
            "",
            3,
            "5D",
            constraint=ConstraintType.START_ON_OR_AFTER,
            constraint_date=date(2026, 6, 10),
        )
    ]
    result = calculate(tasks, [], {"5D": five_day}, data_date=JUN1)
    assert d(result, "INSTALL") == (date(2026, 6, 10), date(2026, 6, 12))
    assert result.violations == ()


def test_start_no_later_than_produces_negative_float_when_it_cannot_be_met(
    five_day,
) -> None:  # type: ignore[no-untyped-def]
    """A(10) then B, but B must start by the 5th. B is five working days late.

    Negative float here is the output, not an error. It is the entire reason the
    planner set the constraint.
    """
    tasks = [
        Task("A", "", 10, "5D"),
        Task(
            "B",
            "",
            2,
            "5D",
            constraint=ConstraintType.START_ON_OR_BEFORE,
            constraint_date=date(2026, 6, 5),
        ),
    ]
    result = calculate(tasks, [Link("A", "B")], {"5D": five_day}, data_date=JUN1)
    assert d(result, "B")[0] == date(2026, 6, 15)
    assert result.total_float_days["B"] == -6
    assert len(result.violations) == 1
    v = result.violations[0]
    assert v.constraint is ConstraintType.START_ON_OR_BEFORE
    assert v.required == date(2026, 6, 5)
    assert v.achieved == date(2026, 6, 15)
    assert v.slip_working_days == 6


def test_finish_no_later_than_produces_negative_float(five_day) -> None:  # type: ignore[no-untyped-def]
    tasks = [
        Task(
            "A",
            "",
            10,
            "5D",
            constraint=ConstraintType.FINISH_ON_OR_BEFORE,
            constraint_date=date(2026, 6, 5),
        )
    ]
    result = calculate(tasks, [], {"5D": five_day}, data_date=JUN1)
    assert result.total_float_days["A"] < 0


def test_a_mandatory_start_overrides_logic_and_pushes_the_predecessor_negative(
    five_day,
) -> None:  # type: ignore[no-untyped-def]
    """A(10) should finish 12 June, but B is pinned to start on the 3rd anyway.

    Modelling this as a soft constraint would leave the dates looking sensible
    and lose the warning. P6 pins it, so we pin it.
    """
    tasks = [
        Task("A", "", 10, "5D"),
        Task(
            "B",
            "",
            2,
            "5D",
            constraint=ConstraintType.MANDATORY_START,
            constraint_date=date(2026, 6, 3),
        ),
    ]
    result = calculate(tasks, [Link("A", "B")], {"5D": five_day}, data_date=JUN1)
    assert d(result, "B")[0] == date(2026, 6, 3)  # logic ignored
    assert result.total_float_days["A"] < 0  # and the predecessor knows


def test_a_mandatory_constraint_in_the_past_yields_to_the_data_date_and_says_so(
    five_day,
) -> None:  # type: ignore[no-untyped-def]
    """You cannot work yesterday. The constraint's failure stays visible."""
    tasks = [
        Task(
            "A",
            "",
            2,
            "5D",
            constraint=ConstraintType.MANDATORY_START,
            constraint_date=date(2026, 5, 1),
        )
    ]
    result = calculate(tasks, [], {"5D": five_day}, data_date=JUN1)
    assert d(result, "A")[0] == date(2026, 6, 1)
    assert len(result.violations) == 1
    assert result.violations[0].overridden_by == "data_date"


def test_as_late_as_possible_consumes_free_float_without_moving_the_finish(
    five_day,
) -> None:  # type: ignore[no-untyped-def]
    """SHORT slides right to meet END, and the project finish does not move."""
    links = [
        Link("START", "LONG"),
        Link("START", "SHORT"),
        Link("LONG", "END"),
        Link("SHORT", "END"),
    ]

    def build(short_constraint: ConstraintType) -> list[Task]:
        return [
            Task("START", "", 1, "5D"),
            Task("LONG", "", 10, "5D"),
            Task("SHORT", "", 4, "5D", constraint=short_constraint),
            Task("END", "", 1, "5D"),
        ]

    plain = calculate(build(ConstraintType.NONE), links, {"5D": five_day}, data_date=JUN1)
    alap = calculate(
        build(ConstraintType.AS_LATE_AS_POSSIBLE), links, {"5D": five_day}, data_date=JUN1
    )

    # Without the constraint SHORT runs as early as it can: Tue 2 to Fri 5 June.
    assert d(plain, "SHORT") == (date(2026, 6, 2), date(2026, 6, 5))
    # With it, SHORT consumes its six days of free float and butts up against
    # END: Wed 10 to Mon 15 June.
    assert d(alap, "SHORT") == (date(2026, 6, 10), date(2026, 6, 15))
    # And the project finish has not moved, which is the whole point of ALAP.
    assert alap.project_finish == plain.project_finish


def test_a_constraint_without_a_date_is_rejected_at_construction() -> None:
    with pytest.raises(ValueError, match="needs a constraint_date"):
        Task("A", "", 1, constraint=ConstraintType.START_ON_OR_AFTER)


def test_must_finish_by_drives_the_backward_pass_negative(five_day) -> None:  # type: ignore[no-untyped-def]
    tasks = [Task("A", "", 10, "5D")]
    result = calculate(
        tasks,
        [],
        {"5D": five_day},
        data_date=JUN1,
        options=SchedulerOptions(must_finish_by=date(2026, 6, 5)),
    )
    assert result.total_float_days["A"] == -5


# -- progress --------------------------------------------------------------


def test_a_completed_activity_has_no_float_rather_than_zero_float(five_day) -> None:  # type: ignore[no-untyped-def]
    """Zero float and "this already happened" are different statements."""
    tasks = [
        Task("A", "", 5, "5D", actual_start=date(2026, 6, 1), actual_finish=date(2026, 6, 5)),
        Task("B", "", 5, "5D"),
    ]
    result = calculate(tasks, [Link("A", "B")], {"5D": five_day}, data_date=date(2026, 6, 8))
    assert result.total_float_days["A"] is None
    assert result.is_critical("A") is False
    assert "A" not in result.critical_ids


def test_remaining_work_starts_at_the_data_date_not_at_the_planned_start(
    five_day,
) -> None:  # type: ignore[no-untyped-def]
    tasks = [Task("A", "", 5, "5D"), Task("B", "", 3, "5D")]
    result = calculate(tasks, [Link("A", "B")], {"5D": five_day}, data_date=date(2026, 6, 15))
    assert d(result, "A")[0] == date(2026, 6, 15)


def test_explicit_remaining_duration_beats_percent_complete(five_day) -> None:  # type: ignore[no-untyped-def]
    """90% complete with 20 days left forecasts 20 days, not 2.

    This is the commonest way an updated schedule lies, and it is why remaining
    duration is a field rather than a derivation.
    """
    issues = IssueLog()
    tasks = [
        Task(
            "A",
            "",
            20,
            "5D",
            actual_start=date(2026, 6, 1),
            remaining_days=20,
            percent_complete=0.9,
        )
    ]
    result = calculate(tasks, [], {"5D": five_day}, data_date=date(2026, 6, 8), issues=issues)
    assert result.statuses["A"].remaining_days == 20
    assert result.statuses["A"].remaining_source == "explicit"
    assert not issues.has("PROGRESS.REMAINING_DERIVED_FROM_PERCENT")


def test_deriving_remaining_from_percent_warns_because_it_assumes_linearity(
    five_day,
) -> None:  # type: ignore[no-untyped-def]
    issues = IssueLog()
    tasks = [Task("A", "", 20, "5D", actual_start=date(2026, 6, 1), percent_complete=0.9)]
    calculate(tasks, [], {"5D": five_day}, data_date=date(2026, 6, 8), issues=issues)
    assert issues.has("PROGRESS.REMAINING_DERIVED_FROM_PERCENT")


def test_an_actual_after_the_data_date_is_an_error_and_is_not_clamped(five_day) -> None:  # type: ignore[no-untyped-def]
    """Clamping fabricates history and makes DCMA check 9 pass on a bad schedule."""
    issues = IssueLog()
    tasks = [Task("A", "", 5, "5D", actual_start=date(2026, 6, 1), actual_finish=date(2026, 6, 20))]
    result = calculate(tasks, [], {"5D": five_day}, data_date=date(2026, 6, 8), issues=issues)
    assert issues.has("PROGRESS.ACTUAL_IN_FUTURE")
    # Saturday 20 June, exactly as recorded -- not snapped onto the Mon-Fri
    # calendar. If the crew worked a Saturday, that is a fact about the job.
    assert day_of(result.early_finish["A"] - 1) == date(2026, 6, 20)


def test_retained_logic_and_progress_override_give_different_answers(five_day) -> None:  # type: ignore[no-untyped-def]
    """The out-of-sequence case, both ways, hand-computed.

    A(10) planned 1-12 June is still running with 8 days left. B(5) started early
    on 8 June and has 5 days left. Data date is Mon 15 June.

    * Retained logic: B still waits for A. A's remaining 8 days run 15-24 June,
      so B runs 25 June - 1 July.
    * Progress override: the link is dropped, B's remaining work starts at the
      data date, 15 June, and finishes 19 June.
    """
    tasks = [
        Task("A", "", 10, "5D", actual_start=date(2026, 6, 1), remaining_days=8),
        Task("B", "", 5, "5D", actual_start=date(2026, 6, 8), remaining_days=5),
    ]
    links = [Link("A", "B")]
    dd = date(2026, 6, 15)

    retained = calculate(
        tasks,
        links,
        {"5D": five_day},
        data_date=dd,
        options=SchedulerOptions(progress_mode=ProgressMode.RETAINED_LOGIC),
    )
    override = calculate(
        tasks,
        links,
        {"5D": five_day},
        data_date=dd,
        options=SchedulerOptions(progress_mode=ProgressMode.PROGRESS_OVERRIDE),
    )

    assert d(retained, "A") == (date(2026, 6, 15), date(2026, 6, 24))
    assert d(retained, "B") == (date(2026, 6, 25), date(2026, 7, 1))
    assert d(override, "B") == (date(2026, 6, 15), date(2026, 6, 19))
    assert retained.project_finish != override.project_finish

    # Progress override must say what it dropped. A mode that silently removes
    # logic is indistinguishable from a bug.
    assert len(override.suppressed_links) == 1
    assert override.suppressed_links[0].predecessor == "A"
    assert retained.suppressed_links == ()


# -- driving path ----------------------------------------------------------


def test_the_driving_path_is_stable_when_the_input_is_shuffled(five_day) -> None:  # type: ignore[no-untyped-def]
    """The source engine's greedy forward walk fails this. Ours must not."""
    tasks = [
        Task("START", "", 1, "5D"),
        Task("L1", "", 5, "5D"),
        Task("L2", "", 5, "5D"),
        Task("R1", "", 3, "5D"),
        Task("END", "", 1, "5D"),
    ]
    links = [
        Link("START", "L1"),
        Link("L1", "L2"),
        Link("L2", "END"),
        Link("START", "R1"),
        Link("R1", "END"),
    ]
    first = calculate(tasks, links, {"5D": five_day}, data_date=JUN1).longest_path()
    for rotation in range(1, len(tasks)):
        shuffled = tasks[rotation:] + tasks[:rotation]
        again = calculate(shuffled, links, {"5D": five_day}, data_date=JUN1).longest_path()
        assert again == first, f"rotation {rotation} changed the driving path"
    assert first == ["START", "L1", "L2", "END"]


def test_two_equally_critical_branches_return_one_stable_named_chain(five_day) -> None:  # type: ignore[no-untyped-def]
    tasks = [
        Task("START", "", 1, "5D"),
        Task("A", "", 5, "5D"),
        Task("B", "", 5, "5D"),
        Task("END", "", 1, "5D"),
    ]
    links = [Link("START", "A"), Link("A", "END"), Link("START", "B"), Link("B", "END")]
    runs = {
        tuple(calculate(tasks, links, {"5D": five_day}, data_date=JUN1).longest_path())
        for _ in range(5)
    }
    assert len(runs) == 1
    path = next(iter(runs))
    assert path[0] == "START" and path[-1] == "END"
    assert len(path) == 3


# -- failure modes ---------------------------------------------------------


def test_a_cycle_is_named_not_merely_detected(five_day) -> None:  # type: ignore[no-untyped-def]
    tasks = [Task("A", "", 1, "5D"), Task("B", "", 1, "5D"), Task("C", "", 1, "5D")]
    links = [Link("A", "B"), Link("B", "C"), Link("C", "A")]
    with pytest.raises(ScheduleCycleError) as excinfo:
        calculate(tasks, links, {"5D": five_day}, data_date=JUN1)
    assert set(excinfo.value.cycle) == {"A", "B", "C"}


def test_an_empty_network_is_refused_rather_than_returning_a_zero_length_project() -> None:
    with pytest.raises(ValueError, match="empty network"):
        calculate([], [], {})


def test_a_missing_calendar_falls_back_and_says_so(five_day) -> None:  # type: ignore[no-untyped-def]
    issues = IssueLog()
    tasks = [Task("A", "", 5, "GHOST")]
    result = calculate(tasks, [], {"5D": five_day}, data_date=JUN1, issues=issues)
    assert issues.has("CPM.CALENDAR_MISSING")
    assert d(result, "A") == (date(2026, 6, 1), date(2026, 6, 5))


def test_summarise_is_json_safe(five_day) -> None:  # type: ignore[no-untyped-def]
    import json

    result = calculate([Task("A", "", 5, "5D")], [], {"5D": five_day}, data_date=JUN1)
    json.dumps(summarise(result))


# -- the precedence stack --------------------------------------------------


def test_the_precedence_stack_holds_when_everything_applies_at_once(five_day) -> None:  # type: ignore[no-untyped-def]
    """One activity subject to all of it at once: a recorded actual start, the
    data date, a mandatory constraint, and retained network logic.

    PRED has not started, so from the data date of Wed 10 June its twenty days
    run to Tue 7 July. SUBJECT started out of sequence on 2 June and has three
    days left; under retained logic that remaining work still waits for PRED, so
    it runs Wed 8 to Fri 10 July.

    The mandatory start on 1 July does *not* apply: the activity has already
    started, so pinning it would move recorded work. It is reported as overridden
    rather than dropped.
    """
    tasks = [
        Task("PRED", "", 20, "5D"),
        Task(
            "SUBJECT",
            "",
            5,
            "5D",
            constraint=ConstraintType.MANDATORY_START,
            constraint_date=date(2026, 7, 1),
            actual_start=date(2026, 6, 2),
            remaining_days=3,
        ),
    ]
    result = calculate(
        tasks, [Link("PRED", "SUBJECT")], {"5D": five_day}, data_date=date(2026, 6, 10)
    )
    # (1) the actual start survives untouched...
    assert result.statuses["SUBJECT"].actual_start is not None
    assert day_of(result.statuses["SUBJECT"].actual_start) == date(2026, 6, 2)
    # (2) the data date floors PRED's unstarted work...
    assert d(result, "PRED") == (date(2026, 6, 10), date(2026, 7, 7))
    # (5) ...and retained logic still governs SUBJECT's remainder.
    assert d(result, "SUBJECT") == (date(2026, 7, 8), date(2026, 7, 10))
    # (3) the mandatory constraint yielded to recorded history, and said so.
    assert len(result.violations) == 1
    assert result.violations[0].overridden_by == "actual_dates"


# -- float that is actually there ------------------------------------------
#
# Both of the following were found by generating random networks and checking
# invariants, not by reading the code. The whole suite passed with the bug in
# place, which is what a randomised probe is for.


def test_an_activity_cannot_finish_after_the_project_does(five_day) -> None:  # type: ignore[no-untyped-def]
    """Late finish is capped at the deadline whether or not there are successors.

    The backward pass took `latest` purely from an activity's successors and
    only fell back to the deadline when there were none. For FS and SS that is
    harmless -- the successor's own late finish already respects the deadline.
    **SF and FF bound the predecessor's start from the successor's finish**,
    which left the predecessor free to finish after the project did.

    By hand, all on Mon-Fri from Monday 1 June 2026:

    * A runs 1--5 June (5 days).
    * B is SF-linked to A with no lag, so B must *finish* on or after A starts.
      B runs 1--10 June (8 days) -- its own earliest start, unconstrained.
    * The project finishes 10 June, the later of the two.

    A finishes 5 June, so it has three working days of float before its own
    finish reaches the 10th. Without the cap its late finish came out well past
    the project end and it reported far more.
    """
    cals = {"5D": five_day}
    tasks = [
        Task(id="A", name="A", duration_days=5, calendar_id="5D"),
        Task(id="B", name="B", duration_days=8, calendar_id="5D"),
    ]
    links = [Link("A", "B", RelationType.SF, 0)]
    result = calculate(tasks, links, cals, data_date=JUN1)

    assert d(result, "A") == (date(2026, 6, 1), date(2026, 6, 5))
    assert d(result, "B") == (date(2026, 6, 1), date(2026, 6, 10))
    assert day_of(result.project_finish - 1) == date(2026, 6, 10)

    # The cap, stated directly: no activity's late finish may exceed the
    # project's finish.
    for aid in ("A", "B"):
        assert result.late_finish[aid] <= result.project_finish, (
            f"{aid} is allowed to finish after the project does"
        )
    assert result.total_float_days["A"] == 3
    assert result.total_float_days["B"] == 0


def test_the_float_it_reports_is_the_float_it_has(five_day) -> None:  # type: ignore[no-untyped-def]
    """The property behind the previous test, measured rather than asserted.

    Delay the activity by exactly its reported total float and the project
    finish must not move; delay it by one more and it must. That is what total
    float *means*, and it is the check that would have caught the bug without
    anybody reasoning about SF semantics at all.
    """
    cals = {"5D": five_day}

    def run(delay_to: date | None):  # type: ignore[no-untyped-def]
        tasks = [
            Task(
                id="A",
                name="A",
                duration_days=5,
                calendar_id="5D",
                constraint=ConstraintType.START_ON_OR_AFTER if delay_to else ConstraintType.NONE,
                constraint_date=delay_to,
            ),
            Task(id="B", name="B", duration_days=8, calendar_id="5D"),
        ]
        return calculate(tasks, [Link("A", "B", RelationType.SF, 0)], cals, data_date=JUN1)

    baseline = run(None)
    float_days = baseline.total_float_days["A"]
    assert float_days == 3

    # Monday 1 June + 3 working days = Thursday 4 June.
    on_the_nose = run(date(2026, 6, 4))
    assert on_the_nose.project_finish == baseline.project_finish, (
        "spending exactly the reported float moved the project"
    )

    one_too_many = run(date(2026, 6, 5))
    assert one_too_many.project_finish > baseline.project_finish, (
        "one day past the reported float did not move the project, so the float is understated"
    )
