"""The baseline schema, plus the default organisation.

Revision ID: 0001_baseline
Revises: 
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from datetime import datetime, timezone


revision = '0001_baseline'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('projects',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('data_date', sa.Date(), nullable=True),
    sa.Column('planned_start', sa.Date(), nullable=True),
    sa.Column('must_finish_by', sa.Date(), nullable=True),
    sa.Column('default_calendar_id', sa.String(length=32), nullable=True),
    sa.Column('progress_mode', sa.Enum('retained_logic', 'progress_override', 'actual_dates', name='progress_mode', native_enum=False, length=32), nullable=False),
    sa.Column('lag_calendar', sa.Enum('predecessor', 'successor', 'twenty_four_hour', 'project_default', name='lag_calendar', native_enum=False, length=32), nullable=False),
    sa.Column('source_format', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'code', name='uq_project_org_code')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index('ix_project_org_name', ['organization_id', 'name'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_organization_id'), ['organization_id'], unique=False)

    op.create_table('activities',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=400), nullable=False),
    sa.Column('kind', sa.Enum('task', 'start_milestone', 'finish_milestone', 'level_of_effort', 'wbs_summary', name='activity_kind', native_enum=False, length=32), nullable=False),
    sa.Column('calendar_key', sa.String(length=64), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('remaining_days', sa.Integer(), nullable=True),
    sa.Column('percent_complete', sa.Float(), nullable=True),
    sa.Column('constraint', sa.Enum('none', 'start_on', 'start_on_or_after', 'start_on_or_before', 'finish_on', 'finish_on_or_after', 'finish_on_or_before', 'as_late_as_possible', 'mandatory_start', 'mandatory_finish', name='constraint_type', native_enum=False, length=32), nullable=False),
    sa.Column('constraint_date', sa.Date(), nullable=True),
    sa.Column('actual_start', sa.Date(), nullable=True),
    sa.Column('actual_finish', sa.Date(), nullable=True),
    sa.Column('computed_start', sa.Date(), nullable=True),
    sa.Column('computed_finish', sa.Date(), nullable=True),
    sa.Column('late_start', sa.Date(), nullable=True),
    sa.Column('late_finish', sa.Date(), nullable=True),
    sa.Column('total_float_days', sa.Integer(), nullable=True),
    sa.Column('free_float_days', sa.Integer(), nullable=True),
    sa.Column('is_critical', sa.Boolean(), nullable=False),
    sa.Column('is_longest_path', sa.Boolean(), nullable=False),
    sa.Column('wbs_code', sa.String(length=120), nullable=False),
    sa.Column('trade', sa.String(length=120), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('extras', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'code', name='uq_activity_project_code')
    )
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activities_project_id'), ['project_id'], unique=False)
        batch_op.create_index('ix_activity_project_critical', ['project_id', 'is_critical'], unique=False)
        batch_op.create_index('ix_activity_project_start', ['project_id', 'computed_start'], unique=False)

    op.create_table('baselines',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('data_date', sa.Date(), nullable=True),
    sa.Column('project_finish', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'name', name='uq_baseline_project_name')
    )
    with op.batch_alter_table('baselines', schema=None) as batch_op:
        batch_op.create_index('ix_baseline_current', ['project_id', 'is_current'], unique=False)
        batch_op.create_index(batch_op.f('ix_baselines_project_id'), ['project_id'], unique=False)

    op.create_table('calendars',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('working_weekdays', sa.JSON(), nullable=False),
    sa.Column('hours_per_day', sa.Float(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'key', name='uq_calendar_project_key')
    )
    with op.batch_alter_table('calendars', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calendars_project_id'), ['project_id'], unique=False)

    op.create_table('import_jobs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=True),
    sa.Column('filename', sa.String(length=400), nullable=False),
    sa.Column('source_format', sa.String(length=16), nullable=False),
    sa.Column('activity_count', sa.Integer(), nullable=False),
    sa.Column('relationship_count', sa.Integer(), nullable=False),
    sa.Column('has_logic', sa.Boolean(), nullable=False),
    sa.Column('issues', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('import_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_import_jobs_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_import_jobs_project_id'), ['project_id'], unique=False)

    op.create_table('resources',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('units_per_day', sa.Float(), nullable=False),
    sa.Column('calendar_key', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'key', name='uq_resource_project_key')
    )
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resources_project_id'), ['project_id'], unique=False)

    op.create_table('assignments',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('activity_id', sa.String(length=32), nullable=False),
    sa.Column('resource_id', sa.String(length=32), nullable=False),
    sa.Column('units_per_day', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('activity_id', 'resource_id', name='uq_assignment')
    )
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assignments_activity_id'), ['activity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assignments_resource_id'), ['resource_id'], unique=False)

    op.create_table('baseline_activities',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('baseline_id', sa.String(length=32), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=400), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('start', sa.Date(), nullable=True),
    sa.Column('finish', sa.Date(), nullable=True),
    sa.Column('total_float_days', sa.Integer(), nullable=True),
    sa.Column('is_critical', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['baseline_id'], ['baselines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('baseline_id', 'code', name='uq_baseline_activity_code')
    )
    with op.batch_alter_table('baseline_activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_baseline_activities_baseline_id'), ['baseline_id'], unique=False)

    op.create_table('calendar_exceptions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('calendar_id', sa.String(length=32), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('working', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['calendar_id'], ['calendars.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('calendar_id', 'day', name='uq_exception_calendar_day')
    )
    with op.batch_alter_table('calendar_exceptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calendar_exceptions_calendar_id'), ['calendar_id'], unique=False)

    op.create_table('relationships',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('predecessor_id', sa.String(length=32), nullable=False),
    sa.Column('successor_id', sa.String(length=32), nullable=False),
    sa.Column('type', sa.Enum('FS', 'SS', 'FF', 'SF', name='relation_type', native_enum=False, length=32), nullable=False),
    sa.Column('lag_days', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['predecessor_id'], ['activities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['successor_id'], ['activities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'predecessor_id', 'successor_id', 'type', name='uq_relationship')
    )
    with op.batch_alter_table('relationships', schema=None) as batch_op:
        batch_op.create_index('ix_relationship_successor', ['successor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_relationships_predecessor_id'), ['predecessor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_relationships_project_id'), ['project_id'], unique=False)

    # ### end Alembic commands ###


    # The default organisation, created here rather than lazily at first use.
    # Every domain row carries `organization_id` from this migration onward;
    # seeding it with the schema means no query and no fixture has to cope with
    # its absence, and two installs of the same version agree on its id.
    op.bulk_insert(
        sa.table(
            "organizations",
            sa.column("id", sa.String),
            sa.column("name", sa.String),
            sa.column("slug", sa.String),
            sa.column("created_at", sa.DateTime),
            sa.column("updated_at", sa.DateTime),
        ),
        [
            {
                "id": "00000000000000000000000000000001",
                "name": "Default",
                "slug": "default",
                "created_at": datetime(2026, 1, 1, tzinfo=timezone.utc),
                "updated_at": datetime(2026, 1, 1, tzinfo=timezone.utc),
            }
        ],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('relationships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_relationships_project_id'))
        batch_op.drop_index(batch_op.f('ix_relationships_predecessor_id'))
        batch_op.drop_index('ix_relationship_successor')

    op.drop_table('relationships')
    with op.batch_alter_table('calendar_exceptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calendar_exceptions_calendar_id'))

    op.drop_table('calendar_exceptions')
    with op.batch_alter_table('baseline_activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_baseline_activities_baseline_id'))

    op.drop_table('baseline_activities')
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assignments_resource_id'))
        batch_op.drop_index(batch_op.f('ix_assignments_activity_id'))

    op.drop_table('assignments')
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resources_project_id'))

    op.drop_table('resources')
    with op.batch_alter_table('import_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_jobs_project_id'))
        batch_op.drop_index(batch_op.f('ix_import_jobs_organization_id'))

    op.drop_table('import_jobs')
    with op.batch_alter_table('calendars', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calendars_project_id'))

    op.drop_table('calendars')
    with op.batch_alter_table('baselines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_baselines_project_id'))
        batch_op.drop_index('ix_baseline_current')

    op.drop_table('baselines')
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_index('ix_activity_project_start')
        batch_op.drop_index('ix_activity_project_critical')
        batch_op.drop_index(batch_op.f('ix_activities_project_id'))

    op.drop_table('activities')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_organization_id'))
        batch_op.drop_index('ix_project_org_name')

    op.drop_table('projects')
    op.drop_table('organizations')
    # ### end Alembic commands ###
